"""Add AuditLog table

Revision ID: 006b90cb21c6
Revises: e7f9a8b3c2d1
Create Date: 2026-02-07 00:38:14.636719

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "006b90cb21c6"
down_revision: Union[str, None] = "e7f9a8b3c2d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.drop_index(op.f("ix_llm_cost_records_created_at"), table_name="llm_cost_records")
    op.drop_index(op.f("ix_llm_cost_records_request_id"), table_name="llm_cost_records")
    op.drop_index(op.f("ix_llm_cost_records_tenant_id"), table_name="llm_cost_records")
    op.drop_index(op.f("ix_llm_cost_records_thread_id"), table_name="llm_cost_records")
    op.drop_index(op.f("ix_llm_cost_records_user_id"), table_name="llm_cost_records")
    op.drop_table("llm_cost_records")
    op.create_unique_constraint(None, "post", ["id"])
    op.create_unique_constraint(None, "rate_limit", ["id"])
    op.create_unique_constraint(None, "tier", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tier", type_="unique")
    op.drop_constraint(None, "rate_limit", type_="unique")
    op.drop_constraint(None, "post", type_="unique")
    op.create_table(
        "llm_cost_records",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("thread_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("provider", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("model_name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("operation", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("input_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("output_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("input_cost_cents", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
        sa.Column("output_cost_cents", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
        sa.Column("total_cost_cents", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("metadata_json", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("llm_cost_records_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_cost_records_pkey")),
    )
    op.create_index(op.f("ix_llm_cost_records_user_id"), "llm_cost_records", ["user_id"], unique=False)
    op.create_index(op.f("ix_llm_cost_records_thread_id"), "llm_cost_records", ["thread_id"], unique=False)
    op.create_index(op.f("ix_llm_cost_records_tenant_id"), "llm_cost_records", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_llm_cost_records_request_id"), "llm_cost_records", ["request_id"], unique=False)
    op.create_index(op.f("ix_llm_cost_records_created_at"), "llm_cost_records", ["created_at"], unique=False)
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
    )
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    # ### end Alembic commands ###
